!!python/object/new:agents.tools.attr_dict.AttrDict
dictitems:
  algorithm: !!python/name:agents.algorithms.ppo.ppo.PPO ''
  discount: 0.995
  env: Xmoto-v0
  eval_episodes: 30
  init_output_factor: 0.1
  init_std: 0.35
  kl_cutoff_coef: 1000
  kl_cutoff_factor: 2
  kl_init_penalty: 1
  kl_target: 0.01
  learning_rate: 0.0001
  logdir: models/20181114T194221-xmoto
  max_length: 10
  network: !!python/name:agents.scripts.networks.feed_forward_categorical ''
  normalize_ranges: true
  num_agents: 1
  optimizer: !!python/name:tensorflow.python.training.adam.AdamOptimizer ''
  policy_layers: !!python/tuple
  - 200
  - 100
  steps: 30000.0
  update_epochs: 25
  update_every: 60
  use_gpu: false
  value_layers: !!python/tuple
  - 200
  - 100
  weight_summaries:
    all: .*
    policy: .*/policy/.*
    value: .*/value/.*
state:
  _mutable: false
